spring:
  datasource:
    url: jdbc:mysql://localhost:3306/samyang?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: ${DB_PASSWORD:pinion}
    driver-class-name: com.mysql.cj.jdbc.Driver
  
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.farm404.samyang.entity
  configuration:
    map-underscore-to-camel-case: false
    
logging:
  level:
    com.farm404.samyang.mapper: DEBUG