-- User 테이블
CREATE TABLE IF NOT EXISTS User (
    UserID INT AUTO_INCREMENT PRIMARY KEY,
    Username VARCHAR(50) NOT NULL UNIQUE,
    Password VARCHAR(255) NOT NULL,
    Email VARCHAR(100) NOT NULL UNIQUE,
    FullName VARCHAR(100) NOT NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Crop 테이블
CREATE TABLE IF NOT EXISTS Crop (
    CropID INT AUTO_INCREMENT PRIMARY KEY,
    CropName VARCHAR(100) NOT NULL,
    ScientificName VARCHAR(200),
    Category VARCHAR(50),
    Description TEXT,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- FarmingDiary 테이블
CREATE TABLE IF NOT EXISTS FarmingDiary (
    DiaryID INT AUTO_INCREMENT PRIMARY KEY,
    UserID INT NOT NULL,
    CropID INT NOT NULL,
    Title VARCHAR(200) NOT NULL,
    Content TEXT NOT NULL,
    WeatherCondition VARCHAR(50),
    Temperature DECIMAL(5,2),
    Humidity DECIMAL(5,2),
    WorkDate DATE NOT NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (UserID) REFERENCES User(UserID) ON DELETE CASCADE,
    FOREIGN KEY (CropID) REFERENCES Crop(CropID) ON DELETE RESTRICT
);

-- Comment 테이블
CREATE TABLE IF NOT EXISTS Comment (
    CommentID INT AUTO_INCREMENT PRIMARY KEY,
    PostID INT NOT NULL,
    UserID INT NOT NULL,
    Content TEXT NOT NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (PostID) REFERENCES FarmingDiary(DiaryID) ON DELETE CASCADE,
    FOREIGN KEY (UserID) REFERENCES User(UserID) ON DELETE CASCADE
);

-- Review 테이블
CREATE TABLE IF NOT EXISTS Review (
    ReviewID INT AUTO_INCREMENT PRIMARY KEY,
    UserID INT NOT NULL,
    CropID INT NOT NULL,
    Rating INT NOT NULL CHECK (Rating >= 1 AND Rating <= 5),
    Title VARCHAR(200) NOT NULL,
    Content TEXT NOT NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (UserID) REFERENCES User(UserID) ON DELETE CASCADE,
    FOREIGN KEY (CropID) REFERENCES Crop(CropID) ON DELETE CASCADE
);

-- Report 테이블
CREATE TABLE IF NOT EXISTS Report (
    ReportID INT AUTO_INCREMENT PRIMARY KEY,
    ReporterID INT NOT NULL,
    TargetType ENUM('diary', 'comment', 'review') NOT NULL,
    TargetID INT NOT NULL,
    Reason VARCHAR(200) NOT NULL,
    Description TEXT,
    Status ENUM('pending', 'resolved', 'rejected') DEFAULT 'pending',
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (ReporterID) REFERENCES User(UserID) ON DELETE CASCADE
);

-- PaymentMethod 테이블
CREATE TABLE IF NOT EXISTS PaymentMethod (
    PaymentMethodID INT AUTO_INCREMENT PRIMARY KEY,
    UserID INT NOT NULL,
    MethodType ENUM('card', 'bank_transfer', 'mobile') NOT NULL,
    MethodName VARCHAR(100) NOT NULL,
    AccountInfo VARCHAR(255),
    IsDefault BOOLEAN DEFAULT FALSE,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (UserID) REFERENCES User(UserID) ON DELETE CASCADE
);